### ISSUE TITLE
How to implement this library in a qmake project

### ISSUE THREAD

**Issue by Megidd** [MASKOR/Qt3DOpenVDBRenderer#1]
The `Qt3DOpenVDBRenderer` is developed by CMake. I have a qmake project which I'm developing with Qt Creator. I wonder if it is possible to use `Qt3DOpenVDBRenderer` in a qmake project. What are the steps to do so? Thanks.

**Comment by dabulla** [comment]
OpenVDB uses CMake, so I think you have to use at least a bit of CMake.
You can just create an empty qmake project and add all the sources of this project manually. Once you compiled OpenVDB you can add it using qmake LIBS. It should actually be quite straight forward. If you added a qmake successfully, I would look forward to a pull request :).

**Comment by Megidd** [comment]
I'm going to work on adding qmake. But I'll need your help 😄
